### ISSUE TITLE
json.decoder.JSONDecodeError retrieving macri-gato

### ISSUE THREAD

**Issue by adalessandro** [mgaitan/radiocut_downloader#13]
See traceback below. Running on radiocut_downloader tag: 0.4

```
$ python -V
Python 3.7.0

$ radiocut http://radiocut.fm/audiocut/macri-gato/ --verbose
Retrieving http://radiocut.fm/audiocut/macri-gato/
Getting chunks index https://chunkserver.radiocut.fm//server/get_chunks/delplata/147812/
Traceback (most recent call last):
  File "/usr/bin/radiocut", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.7/site-packages/radiocut/__init__.py", line 195, in main
    audioclips = [get_audiocut(url, verbose, duration) for url in urls]
  File "/usr/lib/python3.7/site-packages/radiocut/__init__.py", line 195, in <listcomp>
    audioclips = [get_audiocut(url, verbose, duration) for url in urls]
  File "/usr/lib/python3.7/site-packages/radiocut/__init__.py", line 63, in get_audiocut
    chunks_json = requests.get(chunks_url, headers=HEADERS).json()[str(start_folder)]
  File "/usr/lib/python3.7/site-packages/requests/models.py", line 896, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by mgaitan** [comment]
fixed in #14
