### ISSUE TITLE
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by pablolucero** [mgaitan/radiocut_downloader#15]
Hola, intente hacerlo andar y me tira esto en Ubuntu 18.04:

```
$ radiocut http://radiocut.fm/audiocut/macri-gato/ --verbose

Retrieving http://radiocut.fm/audiocut/macri-gato/
Getting chunks index https://chunkserver.radiocut.fm//server/get_chunks/delplata/147812/
Traceback (most recent call last):
  File "/usr/local/bin/radiocut", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/radiocut/__init__.py", line 195, in main
    audioclips = [get_audiocut(url, verbose, duration) for url in urls]
  File "/usr/local/lib/python2.7/dist-packages/radiocut/__init__.py", line 63, in get_audiocut
    chunks_json = requests.get(chunks_url, headers=HEADERS).json()[str(start_folder)]
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 896, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

**Comment by mgaitan** [comment]
@pablolucero confirmá si te sucede con la version de github, porfa

hace poco arreglamos algo similar reportado acá
https://github.com/mgaitan/radiocut_downloader/issues/13

**Comment by zacmaster** [comment]
Buenas. Comento acá para no spammear con otro issue..
Me tira un error al ejecutarlo.. 

radiocut http://radiocut.fm/audiocut/macri-gato/

Traceback (most recent call last):
  File "/usr/local/bin/radiocut", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/radiocut/__init__.py", line 195, in main
    audioclips = [get_audiocut(url, verbose, duration) for url in urls]
  File "/usr/local/lib/python2.7/dist-packages/radiocut/__init__.py", line 63, in get_audiocut
    chunks_json = requests.get(chunks_url, headers=HEADERS).json()[str(start_folder)]
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by camelidus** [comment]
Me pasa lo mismo... Cómo se podrá solucionar? 

Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\radiocut.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\radiocut\__init__.py", line 195, in main
    audioclips = [get_audiocut(url, verbose, duration) for url in urls]
  File "c:\python27\lib\site-packages\radiocut\__init__.py", line 63, in get_aud
iocut
    chunks_json = requests.get(chunks_url, headers=HEADERS).json()[str(start_fol
der)]
  File "c:\python27\lib\site-packages\requests\models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "c:\python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "c:\python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\python27\lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by avdata99** [comment]
Despues de instalar la version oficial probé con 
```
pip install -U git+https://github.com/mgaitan/radiocut_downloader.git
```
y funcionó OK

**Comment by pablolucero** [comment]
con lo que puso @avdata99 anda
