### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by mariano1004** [mgaitan/radiocut_downloader#17]
Hola

No consigo descargar ningún recorte. Esto es lo que me sucede: 

Traceback (most recent call last):
  File "/usr/local/bin/radiocut", line 11, in <module>
    sys.exit(main())
  File "/home/mariano/.local/lib/python2.7/site-packages/radiocut/__init__.py", line 195, in main
    audioclips = [get_audiocut(url, verbose, duration) for url in urls]
  File "/home/mariano/.local/lib/python2.7/site-packages/radiocut/__init__.py", line 63, in get_audiocut
    chunks_json = requests.get(chunks_url, headers=HEADERS).json()[str(start_folder)]
  File "/home/mariano/.local/lib/python2.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

¿Qué puede estar pasando? Intenté lo más básico, que fue actualizar todo lo relacionado a esto, pero sigue ocurriendo lo mismo. 

Gracias!

**Comment by avdata99** [comment]
Me sumo aquí, creo que es un el mismo error.
En mi primer uso probé:
```
radiocut https://radiocut.fm/audiocut/eugenia-monte-este-fallo-es-historico-para-el-feminismo/
```
y el resultado es
```
Traceback (most recent call last):
  File "/usr/local/bin/radiocut", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/radiocut/__init__.py", line 195, in main
    audioclips = [get_audiocut(url, verbose, duration) for url in urls]
  File "/usr/local/lib/python3.6/dist-packages/radiocut/__init__.py", line 195, in <listcomp>
    audioclips = [get_audiocut(url, verbose, duration) for url in urls]
  File "/usr/local/lib/python3.6/dist-packages/radiocut/__init__.py", line 63, in get_audiocut
    chunks_json = requests.get(chunks_url, headers=HEADERS).json()[str(start_folder)]
  File "/home/hudson/.local/lib/python3.6/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by avdata99** [comment]
Despues de instalar la version oficial y que fallara probé con 
```
pip install -U git+https://github.com/mgaitan/radiocut_downloader.git
```
y funcionó OK

**Comment by abonellitoro** [comment]
@avdata99 Anda bárbaro. Mil gracias!

**Comment by abonellitoro** [comment]
@avdata99 Te funcionó con programas enteros?

**Comment by avdata99** [comment]
No probe con programas enteros @abonellitoro

**Comment by monofluor** [comment]
Probe con esto y no logro hacerlo funcionar:

> pip install -U git+https://github.com/mgaitan/radiocut_downloader.git

Me tira:

Traceback (most recent call last):
  File "/usr/local/bin/radiocut", line 10, in <module>
    sys.exit(main())
  File "/home/pablo/.local/lib/python3.7/site-packages/radiocut/__init__.py", line 195, in main
    audioclips = [get_audiocut(url, verbose, duration) for url in urls]
  File "/home/pablo/.local/lib/python3.7/site-packages/radiocut/__init__.py", line 195, in <listcomp>
    audioclips = [get_audiocut(url, verbose, duration) for url in urls]
  File "/home/pablo/.local/lib/python3.7/site-packages/radiocut/__init__.py", line 63, in get_audiocut
    chunks_json = requests.get(chunks_url, headers=HEADERS).json()[str(start_folder)]
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by jschwindt** [comment]
Hora @monofluor! Hace poco Radiocut cambió la forma en que arma las URL de sus API y probablemente por eso dejó de funcionar. Yo ya mandé un PR, pero no está incorporado a este repositorio todavía.
Probá instalarlo desde mi repositorio a ver si te funciona:
```
pip install git+https://github.com/jschwindt/radiocut_downloader.git
```
Si no te anda, mandame un ejemplo de la línea de comando que ejecutás y yo trato de buscar el problema.

**Comment by DrCalambre** [comment]
Hola, quería mencionar que la solución aportada por  jschwindt me sirvió. Un saludo desde la Patagonia Argentina. Muchísimas gracias.

**Comment by MembriyO** [comment]
@jschwindt Entiendo q su repositorio no sigue disponible, existe alguna otra opción para acceder a su versión? En cualquier caso, muchas gracias.

**Comment by jschwindt** [comment]
@MembriyO no quiero tener más problemas con el dueño de RadioCut, pero si te interesa saber qué pasó, escribime a juan@schwindt.org. Saludos!
